---
- name: set file generate command
  set_fact:
    swapfile_generate_command: 'head --bytes={{ swapfile_size }} < /dev/zero > {{ swapfile_location }}'
  when: not (swapfile_use_fallocate | bool)

- name: set file generate command
  set_fact:
    swapfile_generate_command: 'fallocate --length {{ swapfile_size }} {{ swapfile_location }}'
  when: swapfile_use_fallocate | bool

- name: generate swap file
  shell: '{{ swapfile_generate_command }}'
  args:
    creates: '{{ swapfile_location }}'
  register: swapfile_generate_result

- name: set swap file permission
  file:
    path: '{{ swapfile_location }}'
    owner: root
    group: root
    mode: '600'
    state: file

- name: create swap file
  command: 'mkswap {{ swapfile_location }}'
  register: swapfile_mkswap_result
  when: swapfile_generate_result is changed

- name: enable swap file
  command: 'swapon {{ swapfile_location }}'
  when: swapfile_mkswap_result is changed

- name: ensure swap file in fstab
  lineinfile:
    dest: /etc/fstab
    line: '{{ swapfile_location }}   none    swap    sw    0   0'
    state: present

- name: configure vm.swappiness
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'vm.swappiness = {{ swapfile_swappiness }}" regexp="^vm.swappiness[\s]?='
    state: present
  notify: reload sysctl
  when: swapfile_swappiness | bool

- name: configure vm.vfs_cache_pressure
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'vm.vfs_cache_pressure = {{ swapfile_vfs_cache_pressure }}" regexp="^vm.vfs_cache_pressure[\s]?='
    state: present
  notify: reload sysctl
  when: swapfile_vfs_cache_pressure | bool
